In [ ]:
from google.colab import  drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
import random

In [ ]:
data=read_csv("/content/drive/My Drive/sc_lab/heart2.xls")
data=pd.DataFrame(data)
scaler = MinMaxScaler()
scaler.fit(data)
# random.shuffle(data)
data

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
# d1=data[["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]]
# d2=data["target"]
# d1=np.array(d1)
# d2=np.array(d2)
data=data.to_numpy()
random.shuffle(data)
print(data)


[[63.  1.  3. ...  0.  1.  1.]
 [63.  1.  3. ...  0.  1.  1.]
 [63.  1.  3. ...  0.  1.  1.]
 ...
 [52.  1.  1. ...  0.  2.  1.]
 [41.  1.  2. ...  0.  2.  1.]
 [52.  1.  2. ...  4.  2.  1.]]


In [ ]:
d2=data[:,-1]
d1=data[:,:-1]

In [ ]:
n=len(d1[0])
n

13

In [ ]:
def fun(data,N,error,weight,bias,l):
  predict=[0 for i in range(N)]
  
  for i in range(N):
    val=0
    for j in range(n):
      val+=data[i][j]*weight[j]
    val+=bias

    if(val<=0):
      predict[i]=0
    else:
      predict[i]=1

    error[i]=data[i][n]-predict[i]

    for j in range(n):
      if(data[i][j]!=0):
        weight[j]=weight[j]+l*error[i]

  return weight


In [ ]:
def classification_report(cm):
    accuracy = 0
    total = np.sum(cm)
    diagonal = np.sum(np.diag(cm))
    accuracy=(diagonal/total)*100
    print("Accuracy : => ",(diagonal/total)*100)
    return accuracy

In [ ]:
block=int(len(data)/10)
print(block)
M=[[ 0 for i in range(2)] for i in range(2)]
for i in range(10):

  L=0.2
  bias=0
  temp_x_data=[]
  temp_y_data=[]
  
  x_test=[]
  y_test=[]
  

  point=[]
  for j in range(block):
    point.append(block*i+j)

  
  for j in range(len(data)):
    if(j in point):
      x_test.append(d1[j])
      y_test.append(d2[j])
    else:
      temp_x_data.append(d1[j])
      temp_y_data.append(d2[j])


  
  matrix=[[0 for i in range(2)]for i in range(2)]

  weight=[1/n for i in range(n)]
  error=[1 for i in range(len(temp_x_data))]
  
  max_itr=500
  while(max_itr):
    w=fun(data,len(temp_x_data),error,weight,bias,L)
    weight=w
    max_itr-=1

  for j in range(len(x_test)):
    val=0
    for k in range(n):
      val+=x_test[j][k]*weight[k]
    val+=bias
  
    if(val<=0):
      matrix[int(y_test[j])][0]+=1
    else:
      matrix[int(y_test[j])][1]+=1

  for p in range(2):
    for q in range(2):
      M[p][q]+=matrix[p][q]
  print("Fold ",i+1)
  print(matrix)
  accu=classification_report(matrix)

print("Final confusion matrix")
print(M)
print()
print("Average accuracy=>",classification_report(M))

30
Fold  1
[[0, 0], [0, 30]]
Accuracy : =>  100.0
Fold  2
[[0, 0], [1, 29]]
Accuracy : =>  96.66666666666667
Fold  3
[[0, 0], [3, 27]]
Accuracy : =>  90.0
Fold  4
[[0, 0], [0, 30]]
Accuracy : =>  100.0
Fold  5
[[0, 0], [1, 29]]
Accuracy : =>  96.66666666666667
Fold  6
[[2, 0], [1, 27]]
Accuracy : =>  96.66666666666667
Fold  7
[[1, 1], [0, 28]]
Accuracy : =>  96.66666666666667
Fold  8
[[6, 0], [1, 23]]
Accuracy : =>  96.66666666666667
Fold  9
[[3, 4], [1, 22]]
Accuracy : =>  83.33333333333334
Fold  10
[[10, 4], [3, 13]]
Accuracy : =>  76.66666666666667
Final confusion matrix
[[22, 9], [11, 258]]

Accuracy : =>  93.33333333333333
Average accuracy=> 93.33333333333333
